[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo     = 'Shougo/vimfiler'
hook_add = '''
let g:vimfiler_safe_mode_by_default = 0
let g:vimfiler_ignore_pattern = [
  \ '^\.DS_Store$',
  \ '^__pycache__$',
  \ '\.egg-info$',
  \ '\.pyc$'
  \ ]
autocmd FileType vimfiler setlocal nonumber
nnoremap <silent> ,vf :<C-u>VimFilerExplorer<CR>
'''

[[plugins]]
repo     = 'Shougo/unite.vim'
hook_add = '''
let g:unite_prompt = '> '
" insertモードをデフォルトにしない
let g:unite_enable_start_insert = 0
let g:unite_source_history_yank_enable =1
" 無指定にすることで高速化
let g:unite_source_file_mru_filename_format = ''
" most recently used のリストサイズ
let g:unite_source_file_mru_limit = 100
" Unite起動時のウィンドウ分割
let g:unite_split_rule = 'rightbelow'
" 使わないデフォルト Unite ソースをロードしない
let g:loaded_unite_source_bookmark = 1
let g:loaded_unite_source_window = 1

nnoremap <silent> ,uy :<C-u>Unite history/yank<CR>
nnoremap <silent> ,ub :<C-u>Unite buffer<CR>
nnoremap <silent> ,uf :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> ,ur :<C-u>Unite -buffer-name=register register<CR>
nnoremap <silent> ,uu :<C-u>Unite file_mru buffer<CR>

nnoremap  [unite]  <Nop>
nmap      <Space>u [unite]
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimshell'
rev  = '3787e5'

[[plugins]]
repo     = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo     = 'majutsushi/tagbar'
hook_add = '''
nmap <F8> :TagbarToggle<CR>
'''

[[plugins]]
repo     = 'junegunn/vim-easy-align'
on_map   = ['<Plug>(EasyAlign)']
hook_add = '''
vmap <Enter> <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'
hook_add = '''
au MyAutoCmd VimEnter * nested colorscheme lucius
let g:lucius_style = 'dark'
let g:lucius_contrast = 'normal'
let g:lucius_contrast_bg = 'normal'
'''

[[plugins]]
repo = 'jeffreyiacono/vim-colors-wombat'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {'colorscheme': 'wombat'}
'''

#[[plugins]]
#repo = 'rhysd/wallaby.vim'
#hook_add = '''
#au MyAutoCmd VimEnter * nested colorscheme wallaby
#'''

#[[plugins]]
#repo     = 'junegunn/seoul256.vim'
#hook_add = '''
#let g:seoul256_background = 235
#au MyAutoCmd VimEnter * nested colorscheme seoul256
#'''

[[plugins]]
repo = 'jnurmine/Zenburn'

[[plugins]]
repo = 'croaker/mustang-vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'mrkn/mrkn256.vim'

[[plugins]]
repo = 'therubymug/vim-pyte'

[[plugins]]
repo = 'derekwyatt/vim-scala'

