[[plugins]]
repo  = 'vim-python/python-syntax'
on_ft = 'python'
hook_source = '''
let g:python_highlight_all = 1
'''

[[plugins]]
repo  = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo  = 'andviro/flake8-vim'
on_ft = 'python'

[[plugins]]
repo  = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
let g:jedi#goto_command = ",jd"
let g:jedi#goto_assignments_command = ",jg"
let g:jedi#rename_command = ",jr"
let g:jedi#usages_command = ",jn"
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo  = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo  = 'neovim/python-client'
on_ft = 'python'

#[[plugins]]
#repo = 'Shougo/neocomplete.vim'
#on_i = 1

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#[[plugins]]
#repo = 'maralla/vim-toml-enhance'
#on_ft = ['toml']
#depends = ['cespare/vim-toml']
#depends = ['vim-toml']

#[[plugins]]
#repo = 'stephpy/vim-yaml'
#on_ft = ['yaml']

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'rst', 'mkd']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'rst', 'mkd']
depends = ['vim-markdown']
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'previm/previm'
on_cmd = 'PrevimOpen'
depends = ['open-browser.vim']
